#!/bin/sh
userresources=$XDG_CONFIG_HOME/X11/Yresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi
[[ -f "$usermodmap" ]] && xmodmap "$usermodmap"

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5

touch $XDG_RUNTIME_DIR/Xauthority

exec /usr/bin/i3
